version: "3"
services:
  develop:
    build: .
    env_file:
      - dev.env
    ports:
      - "3200:3200"
    container_name: gfw-ogr-api-develop
    command: develop
    volumes:
      - ./app:/opt/gfw-ogr-api/app
      
networks:
  default:
    external:
      name: control-tower_controltower
